# Generated by Django 5.0.3 on 2024-04-30 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vgadmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branches',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
