# Generated by Django 5.0.3 on 2024-03-14 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productmanagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('quantity', models.IntegerField()),
                ('primary_image', models.ImageField(upload_to='product_images/')),
            ],
        ),
        migrations.CreateModel(
            name='SecondaryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_images/secondary/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productmanagement.product')),
            ],
        ),
    ]
