# Generated by Django 5.0.3 on 2024-03-15 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productmanagement', '0002_product_secondaryimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_acitve',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
