# Generated by Django 5.0.3 on 2024-03-15 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productmanagement', '0003_category_is_acitve_product_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='is_acitve',
            new_name='is_active',
        ),
    ]
