# Generated by Django 5.0.3 on 2024-04-23 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productmanagement', '0009_product_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit_type',
            field=models.CharField(choices=[('g', 'G'), ('kg', 'Kg'), ('l', 'L')], default='kg', max_length=10),
        ),
    ]
