# Generated by Django 5.0.3 on 2024-05-01 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productmanagement', '0015_alter_categoryoffer_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit_type',
            field=models.CharField(choices=[('g', 'G'), ('l', 'L'), ('kg', 'Kg')], default='kg', max_length=10),
        ),
        migrations.AlterField(
            model_name='productoffer',
            name='discount',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
