# Generated by Django 5.0.3 on 2024-05-01 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productmanagement', '0017_categoryoffer_status_productoffer_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit_type',
            field=models.CharField(choices=[('g', 'G'), ('l', 'L'), ('kg', 'Kg')], default='kg', max_length=10),
        ),
    ]
