# Generated by Django 5.0.3 on 2024-05-01 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productmanagement', '0020_product_special_discount_alter_product_unit_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='max_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_type',
            field=models.CharField(choices=[('kg', 'Kg'), ('g', 'G'), ('l', 'L')], default='kg', max_length=10),
        ),
    ]
