# Generated by Django 5.0.3 on 2024-05-02 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productmanagement', '0021_product_max_discount_alter_product_unit_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit_type',
            field=models.CharField(choices=[('g', 'G'), ('kg', 'Kg'), ('l', 'L')], default='kg', max_length=10),
        ),
    ]
