# Generated by Django 5.0.3 on 2024-05-14 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productmanagement', '0027_alter_product_special_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='special_discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_type',
            field=models.CharField(choices=[('kg', 'Kg'), ('g', 'G'), ('l', 'L')], default='kg', max_length=10),
        ),
    ]
