# Generated by Django 5.0.3 on 2024-06-11 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productmanagement', '0060_alter_product_unit_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit_type',
            field=models.CharField(choices=[('kg', 'Kg'), ('g', 'G'), ('l', 'L')], default='kg', max_length=10),
        ),
    ]
