# Generated by Django 5.0.3 on 2024-03-13 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vguser',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
