# Generated by Django 5.0.3 on 2024-06-12 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_vguser_is_blocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='vguser',
            name='is_google',
            field=models.BooleanField(default=False),
        ),
    ]
