# Generated by Django 5.0.3 on 2024-03-21 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_useraddress_delete_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='phone_number',
            field=models.IntegerField(default=67),
            preserve_default=False,
        ),
    ]
