# Generated by Django 5.0.3 on 2024-03-21 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_useraddress_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='landmark',
            field=models.CharField(default=54, max_length=65),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useraddress',
            name='pincode',
            field=models.PositiveIntegerField(default=44),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='phone_number',
            field=models.PositiveIntegerField(),
        ),
    ]
