# Generated by Django 5.0.3 on 2024-03-21 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_useraddress_landmark_useraddress_pincode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraddress',
            name='postal_code',
        ),
    ]
