# Generated by Django 5.0.3 on 2024-05-01 08:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_whishlist_whishlistitem'),
        ('productmanagement', '0019_alter_product_unit_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Whishlist',
            new_name='Wishlist',
        ),
        migrations.RenameModel(
            old_name='WhishlistItem',
            new_name='WishlistItem',
        ),
    ]
