# Generated by Django 5.0.3 on 2024-05-14 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0017_cart_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='location',
        ),
    ]
