# Generated by Django 5.0.3 on 2024-05-15 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0025_cart_coupon_total'),
        ('vgadmin', '0005_coupon_used_by_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='select_coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vgadmin.coupon'),
        ),
    ]
