# Generated by Django 5.0.3 on 2024-05-25 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0028_alter_wallet_amount_alter_wallet_user_wallethistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='previous_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
