# Generated by Django 5.0.3 on 2024-06-10 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0029_wallet_previous_balance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraddress',
            old_name='state',
            new_name='district',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='coupon_total',
        ),
    ]
