# Generated by Django 5.0.3 on 2024-04-17 10:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordermanagement', '0002_orderitem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='item_created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='payment_status',
            field=models.CharField(choices=[('completed', 'Completed'), ('pending', 'Pending'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('cancelled', 'Cancelled'), ('pending', 'Pending'), ('placed', 'Placed'), ('delivered', 'Delivered'), ('return_requested', 'Return Requested'), ('returned', 'Returned'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
