# Generated by Django 5.0.3 on 2024-04-22 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordermanagement', '0003_orderitem_item_created_at_orderitem_payment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Cod'), ('wallet', 'Wallet'), ('razorpay', 'Razorpay')], max_length=20),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('cancelled', 'Cancelled'), ('pending', 'Pending'), ('delivered', 'Delivered'), ('return_requested', 'Return Requested'), ('returned', 'Returned'), ('failed', 'Failed'), ('proccessing', 'Proccessing'), ('in_transit', 'In transit')], default='pending', max_length=20),
        ),
    ]
