# Generated by Django 5.0.3 on 2024-04-30 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordermanagement', '0006_alter_orderitem_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='user_cancel',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('failed', 'Failed'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
