# Generated by Django 5.0.3 on 2024-05-03 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordermanagement', '0017_order_razorpayid_alter_orderitem_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='payment_status',
            field=models.CharField(choices=[('failed', 'Failed'), ('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
