# Generated by Django 5.0.3 on 2024-05-28 02:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordermanagement', '0050_alter_orderitem_payment_status'),
        ('productmanagement', '0058_alter_product_unit_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='key_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='productmanagement.product'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='payment_status',
            field=models.CharField(choices=[('completed', 'Completed'), ('failed', 'Failed'), ('pending', 'Pending')], default='pending', max_length=20),
        ),
    ]
